FROM node:lts-buster

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    LC_CTYPE="utf-8"

RUN apt -y update \
    && apt -y install \
    vim

RUN npm config set registry https://registry.npm.taobao.org \
    && npm install -g create-nuxt-app

RUN mkdir front
WORKDIR /front
